// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTQDj-3K3GGFxOcyhXB0v8YLEa4bd5Xw',
    appId: '1:604310307169:web:ee19c4b474af20fc544520',
    messagingSenderId: '604310307169',
    projectId: 'projeto-estoico',
    authDomain: 'projeto-estoico.firebaseapp.com',
    storageBucket: 'projeto-estoico.appspot.com',
    measurementId: 'G-QTT9WXEPTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bVoIXsMmst15GvcvFzHFk9Mxucy6oJk',
    appId: '1:604310307169:android:7773b4ab72f0cc7a544520',
    messagingSenderId: '604310307169',
    projectId: 'projeto-estoico',
    storageBucket: 'projeto-estoico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkUfWFOjZAwb3VpNU2NlePe5pzJxpfmBU',
    appId: '1:604310307169:ios:8af6b124b37c0272544520',
    messagingSenderId: '604310307169',
    projectId: 'projeto-estoico',
    storageBucket: 'projeto-estoico.appspot.com',
    iosBundleId: 'com.example.projetoEstoico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkUfWFOjZAwb3VpNU2NlePe5pzJxpfmBU',
    appId: '1:604310307169:ios:22f9ba6e63ab1f80544520',
    messagingSenderId: '604310307169',
    projectId: 'projeto-estoico',
    storageBucket: 'projeto-estoico.appspot.com',
    iosBundleId: 'com.example.projetoEstoico.RunnerTests',
  );
}
